###
get http://localhost:8081/api/v1/employers

###
# put url http://localhost:8081/api/v1/register

# Content-Type: application/json
# {
# "Id":3
# "Name":"Jan Kowalski"
# "Email":"jan.kowalski@gmail.com"
# "PhoneNumber":"6-321-54321"
# }

# <> 2023-02-22T18-12-39.json

###
POST http://localhost:8081/api/v1/employers
Content-Type: application/json

{
"name":"Jan Kowalski",
"email":"jan.kowalski@gmail.com",
"phoneNumber":"6-321-54321"
}
###
DELETE http://localhost:8081/api/v1/employers/3
Content-Type: application/json

{
"name":"Jan Kowalski",
"email":"jan.kowalski@gmail.com",
"phoneNumber":"6-321-54321"
}